### ISSUE TITLE
Xcode 13 Build Error

### ISSUE THREAD

**Issue by rlaurente** [light-tech/SwiftGit2-SampleApp#1]
Hi There

I tried cloning and build it directly with xcode 13 but I got this errors below. Does this related to swift version ?

Thanks

![Screen Shot 2021-11-02 at 2 20 33 PM](https://user-images.githubusercontent.com/1804380/139922981-d09293d9-8f45-436b-a8e4-deb1907a6f04.png)

**Comment by light-tech** [comment]
> Does this related to swift version ?

It wasn't. It was because our script failed to build the library for the simulator: It only works for Mac Catalyst and real iPhone. Just updated the Clibgit2 package to fix the issue. Thanks for reporting.
